on:
  push: 
    branches: 
      - main
  pull_request: 
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Archive jars
        uses: actions/upload-artifact@v3
        with:
          name: fabric
          path: fabric/build/libs/*.jar